import api from '../api/client'
import type { AnalysisResponse } from '../types/analysis'

/** Trigger a client-side file download from a string or Blob. */
function download(filename: string, content: string | Blob, mime: string) {
  const blob = content instanceof Blob ? content : new Blob([content], { type: mime })
  const url = URL.createObjectURL(blob)
  const a = document.createElement('a')
  a.href = url
  a.download = filename
  document.body.appendChild(a)
  a.click()
  a.remove()
  URL.revokeObjectURL(url)
}

function slug(result: AnalysisResponse): string {
  const name = result.parsed.name?.trim() || 'profile'
  return name.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '')
}

export function exportJson(result: AnalysisResponse) {
  download(`${slug(result)}-report.json`, JSON.stringify(result, null, 2), 'application/json')
}

/** Build a clean, human-readable Markdown report from the analysis. */
export function buildMarkdown(result: AnalysisResponse): string {
  const { scores, parsed, recommendations, strengths, weaknesses, career_predictions, ai_writing } = result
  const stripPts = (s: string) => s.replace(/\s*\(~\+\d+ pts\)\s*$/, '')
  const lines: string[] = []

  lines.push(`# LinkedIn Profile Report${parsed.name ? ` — ${parsed.name}` : ''}`)
  if (parsed.headline) lines.push(`_${parsed.headline}_`)
  lines.push('')
  lines.push(`**Overall score: ${scores.overall}/100**${result.ml_used ? ' (ML-calibrated)' : ''}`)
  lines.push('')

  lines.push('## Scores')
  lines.push('| Dimension | Score |')
  lines.push('| --- | --- |')
  lines.push(`| Completeness | ${scores.completeness} |`)
  lines.push(`| Technical Strength | ${scores.technical} |`)
  lines.push(`| Recruiter Appeal | ${scores.recruiter} |`)
  lines.push(`| ATS Score | ${scores.ats} |`)
  lines.push(`| Leadership | ${scores.leadership} |`)
  lines.push(`| Networking | ${scores.networking} |`)
  lines.push(`| Career Readiness | ${scores.career_readiness} |`)
  lines.push('')

  if (career_predictions.length) {
    lines.push('## Career Match')
    for (const c of career_predictions) lines.push(`- **${c.role}** — ${c.match_pct}%`)
    lines.push('')
  }

  if (strengths.length) {
    lines.push('## Strengths')
    for (const s of strengths) lines.push(`- ${s}`)
    lines.push('')
  }
  if (weaknesses.length) {
    lines.push('## Weaknesses')
    for (const w of weaknesses) lines.push(`- ${w}`)
    lines.push('')
  }

  if (recommendations.length) {
    lines.push('## Recommendations (highest impact first)')
    for (const r of recommendations) {
      const pts = r.impact_points ? ` _(~+${r.impact_points} pts)_` : ''
      lines.push(`- ${stripPts(r.content)}${pts}`)
      if (r.example) lines.push(`  - e.g. ${r.example}`)
    }
    lines.push('')
  }

  if (ai_writing.headline || ai_writing.about) {
    lines.push('## AI Writing Suggestions')
    if (ai_writing.headline) {
      lines.push('**Headline**')
      lines.push('')
      lines.push(ai_writing.headline)
      lines.push('')
    }
    if (ai_writing.about) {
      lines.push('**About**')
      lines.push('')
      lines.push(ai_writing.about)
      lines.push('')
    }
  }

  lines.push('---')
  lines.push(`Generated by LinkedIn AI Coach on ${new Date().toLocaleString()}.`)
  return lines.join('\n')
}

export function exportMarkdown(result: AnalysisResponse) {
  download(`${slug(result)}-report.md`, buildMarkdown(result), 'text/markdown')
}

/**
 * Download a server-generated, recruiter-style PDF report.
 *
 * Posts the in-memory result (full fidelity — preserves impact points and
 * worked examples that aren't all persisted) and saves the returned PDF.
 */
export async function exportPdf(result: AnalysisResponse) {
  const { data } = await api.post<Blob>('/report/pdf', result, { responseType: 'blob' })
  download(`${slug(result)}-report.pdf`, data, 'application/pdf')
}

/** Open the browser print dialog (user can Save as PDF). */
export function printReport() {
  window.print()
}
